### PR TITLE
chore/deploy-to-heroku

### PR DESCRIPTION
**Pull request by saszaCodes**
#### What does this PR do?
Makes changes necessary to pass ESLint checks before deploying to Heroku. Files changed comparing to main branch: App.js (added JSDoc comment) and reportWebVitals.js (a few stylistic changes)

#### Description of Task to be completed?
Deploying the app to Heroku

#### How should this be manually tested?
Working app can be chcecked here: [https://interactive-timer.herokuapp.com/](url) (it may take a moment for server to wake up). To test if files pass ESLint checks, run `npm run lint [path/to/file]` on App.js and reportWebVitals.js

#### Questions:
- When I tried to push to Heroku right after cloning the current code from the main branch, an error was thrown and the message urged me to run `yarn install` and then commit the updated `yarn.lock` file. Why is that? What does the `yarn.lock` file do? I was expecting it to work without making any changes to the repo, because, as I understand, Heroku installs dependencies by itself when a new version is pushed to the Heroku's main branch, and then runs the `"start"` script defined in the `package.json` file. Is that not the case?

### CODE REVIEW

**Comment by Avuidrauxs** [comment]
@tepeszCodes , add a script to run linting on the entire app 

eg.

```
npm run lint   // runs eslint rules all our source files except our builds
```

Also, I was expecting to see some changes in our package.json file with scripts for Heroku CLI deployment

**Comment by Avuidrauxs** [comment]
`yarn.lock` is a file that makes sure your dependency trees are consistent whenever you run a new `yarn` operation on your `node_modules` folder

**Comment by saszaCodes** [comment]
@Avuidrauxs I implemented the changes you requested

**Review by Avuidrauxs — APPROVED** [review]
Looks Good.

**Pull request merged**
